intent_data = {
    "greet": [
        {"query": "hi", "response": "Hello!"},
        {"query": "hello", "response": "Hi there!"},
        {"query": "hey", "response": "Hey!"},
        {"query": "howdy", "response": "Howdy!"},
        {"query": "good morning", "response": "Good morning!"},
        {"query": "good afternoon", "response": "Good afternoon!"},
        {"query": "good evening", "response": "Good evening!"},
        {"query": "yo", "response": "Yo!"},
        {"query": "what's up", "response": "Not much, just here to assist you."},
        {"query": "nice to meet you", "response": "Nice to meet you too!"},
        {"query": "how's your day", "response": "My day's going well, thanks for asking!"},
        {"query": "good to see you", "response": "Good to see you too!"},
        {"query": "how have you been", "response": "I've been good, thanks!"},
        {"query": "long time no see", "response": "Yes, it has been a while!"},
        {"query": "what's cracking", "response": "Not much, just here to assist you!"},
        {"query": "pleased to meet you", "response": "Likewise!"},
        {"query": "hi there", "response": "Hello!"},
        {"query": "how's it hanging", "response": "It's going well, thank you. How about you?"},
        {"query": "top of the morning", "response": "And the rest of the day to you!"},
        {"query": "what's happening", "response": "Not much, just here to assist you."},
    
    ],
    "ask_how_are_you": [
        {"query": "how are you", "response": "I'm fine, thank you. How about you?"},
        {"query": "how's it going", "response": "It's going well, thank you. How about you?"},
        {"query": "what's up", "response": "Not much, just here to assist you. How are you?"},
        {"query": "how are you doing", "response": "I'm doing great! Thanks for asking."},
        {"query": "how's your day", "response": "My day is going well, thanks for asking. How about yours?"},
        {"query": "how have you been", "response": "I've been good. How about you?"},
        {"query": "how are things", "response": "Things are going smoothly. What about you?"},
        {"query": "are you okay", "response": "Yes, I'm okay. How about you?"},
        {"query": "how's life", "response": "Life is good, thanks for asking. How about yours?"},
        {"query": "how's everything", "response": "Everything's going well. What about you?"},
        {"query": "how's your day been", "response": "My day has been good, thank you. How about yours?"},
        {"query": "how's your health", "response": "I'm in good health, thank you for asking. How about you?"},
        {"query": "how's work", "response": "Work's been good, thanks for asking. How about yours?"},
        {"query": "how's the weather", "response": "The weather's been nice. How about where you are?"},
        {"query": "how's your family", "response": "My family is well, thanks for asking. How about yours?"},
        {"query": "how's school", "response": "School's been good, thanks for asking. How about yours?"},
        {"query": "how's your day going", "response": "My day is going well, thanks for asking. How about yours?"},
        {"query": "how's your weekend", "response": "My weekend has been good, thank you. How about yours?"},
        {"query": "how are you feeling", "response": "I'm feeling good. Thanks for asking."},
        {"query": "how's the day treating you", "response": "The day is treating me well. How about you?"},
    ],
    "farewell": [
        {"query": "goodbye", "response": "Goodbye! Take care."},
        {"query": "bye", "response": "Bye! Have a great day."},
        {"query": "see you later", "response": "See you later!"},
        {"query": "take care", "response": "You too!"},
        {"query": "until next time", "response": "Until next time!"},
        {"query": "have a good one", "response": "You too!"},
        {"query": "bye-bye", "response": "Bye-bye!"},
        {"query": "farewell", "response": "Farewell!"},
        {"query": "so long", "response": "So long!"},
        {"query": "catch you later", "response": "Catch you later!"},
        {"query": "talk to you soon", "response": "Talk to you soon!"},
        {"query": "goodnight", "response": "Goodnight!"},
        {"query": "sleep well", "response": "You too!"},
        {"query": "see you tomorrow", "response": "See you tomorrow!"},
        {"query": "have a great day", "response": "You too!"},
        {"query": "bye for now", "response": "Bye for now!"},
        {"query": "see you around", "response": "See you around!"},
        {"query": "have a nice day", "response": "You too!"},
        {"query": "bye then", "response": "Goodbye!"},
        {"query": "later", "response": "Later!"},
    ],
    "gratitude": [
        {"query": "thank you", "response": "You're welcome!"},
        {"query": "thanks", "response": "No problem!"},
        {"query": "appreciate it", "response": "Glad to help!"},
        {"query": "thank you so much", "response": "You're welcome!"},
        {"query": "thanks a bunch", "response": "Anytime!"},
        {"query": "much obliged", "response": "My pleasure!"},
        {"query": "thanks a million", "response": "Happy to assist!"},
        {"query": "thanks a ton", "response": "No worries!"},
        {"query": "you're the best", "response": "Thanks! You're pretty great too!"},
        {"query": "I owe you one", "response": "No problem at all!"},
        {"query": "I appreciate your help", "response": "I'm here to help anytime!"},
        {"query": "thanks for your assistance", "response": "You're welcome!"},
        {"query": "thanks for your support", "response": "Glad to be of assistance!"},
        {"query": "thanks for everything", "response": "Anything for you!"},
        {"query": "thanks for being there", "response": "Always here for you!"},
        {"query": "thank you for your time", "response": "Of course, happy to help!"},
        {"query": "thanks for the help", "response": "No problem at all!"},
        {"query": "I'm grateful", "response": "I'm happy to assist!"},
        {"query": "thanks for listening", "response": "Always here to listen!"},
        {"query": "you're amazing", "response": "Thank you! You're amazing too!"},
    ],
    "apology": [
        {"query": "sorry", "response": "No problem, it happens!"},
        {"query": "my apologies", "response": "No worries!"},
        {"query": "I apologize", "response": "It's okay!"},
        {"query": "I'm sorry", "response": "No need to apologize!"},
        {"query": "forgive me", "response": "Of course, all is forgiven!"},
        {"query": "sorry about that", "response": "No problem at all!"},
        {"query": "I'm really sorry", "response": "It's alright, don't worry!"},
        {"query": "my bad", "response": "No harm done!"},
        {"query": "I'm so sorry", "response": "It's okay, no harm done!"},
        {"query": "please forgive me", "response": "Of course, all is forgiven!"},
        {"query": "I'm terribly sorry", "response": "No worries, it happens!"},
        {"query": "sorry for the inconvenience", "response": "It's alright, no worries!"},
        {"query": "I'm deeply sorry", "response": "No problem, all is forgiven!"},
        {"query": "I apologize for that", "response": "No need to apologize!"},
        {"query": "sorry about the confusion", "response": "No problem at all!"},
        {"query": "I'm extremely sorry", "response": "It's okay, no harm done!"},
        {"query": "sorry for the misunderstanding", "response": "It's alright, no worries!"},
        {"query": "please accept my apologies", "response": "Of course, all is forgiven!"},
        {"query": "sorry to hear that", "response": "It's okay, no problem!"},
        {"query": "sorry for the trouble", "response": "No worries at all!"},
    ],
    # Add more intents with example queries and responses as needed
}

